syntax = "proto3";
package circuits_v2;
option csharp_namespace = "CircuitsV2.Protobuf";

import "core/guid_data.proto";

enum CircuitStudioUnitySubAssetKind {
  AudioClip = 0;
  Projectile = 1;
  ParticleVfx = 2;
}

message CircuitStudioUnitySubAssetUsageData {	
  repeated CircuitStudioUnitySubAssetUsageEntryData unity_assets = 1;
}

message CircuitStudioUnitySubAssetUsageEntryData {	
  core.GuidData unity_asset_id = 1;
  repeated core.GuidData referenced_unity_asset_ids = 2;
  CircuitStudioUnitySubAssetKind unity_asset_kind = 3;
}
