syntax = "proto3";
package circuits_v2;
option csharp_namespace = "CircuitsV2.Protobuf";

import "circuits/shared/api/id_128_data.proto";

import "circuits/shared/utilities/soa_id_32_data.proto";

import "circuits/static/core/tree_system/tree_sys_data.proto";

import "circuits_v2/graph/in_out_graph_inst_data.proto";
import "circuits_v2/graph/state_machine_graph_inst_data.proto";
import "circuits_v2/graph/behavior_graph_inst_data.proto";

import "circuits_v2/behaviors/behaviors_state_data.proto";
import "circuits_v2/circuit_graph_entities_data.proto";
import "circuits_v2/function_decl_inst_data.proto";
import "circuits_v2/function_def_graph_inst_data.proto";
import "circuits_v2/messages/messages_state_data.proto";
import "circuits_v2/custom_properties_state_data.proto";
import "circuits_v2/room_assets_state_data.proto";

message CircuitGlobalEntitiesData {
  circuits.TreeSysData graph_hierarchy = 1;
  repeated int32 graph_def_ids = 2;
  repeated int32 graph_join_ids = 3;
  repeated CircuitGraphEntitiesData graph_entities = 4;
  repeated circuits.Id128Data legacy_graph_ids = 5;

  circuits.SOAId32Data in_out_graph_ids = 6;
  repeated InOutGraphInstData in_out_graph_insts = 7;

  circuits.SOAId32Data state_machine_graph_ids = 8;
  repeated StateMachineGraphInstData state_machine_graph_insts = 9;

  circuits.SOAId32Data function_decl_ids = 10;
  repeated FunctionDeclInstData function_decls = 11;
  repeated string function_decl_names = 14;

  circuits.SOAId32Data function_def_graph_ids = 12;
  repeated FunctionDefGraphInstData function_def_graphs = 13;

  circuits.SOAId32Data behavior_graph_ids = 20;
  repeated BehaviorGraphInstData behavior_graph_insts = 21;

  CustomPropertiesStateData object_properties_state_data = 15;

  RoomAssetsStateData room_assets_state_data = 16;

  CustomPropertiesStateData player_properties_state_data = 17;

  MessagesStateData messages_state = 18;

  BehaviorsStateData behaviors_state = 19;

  circuits.SOAId32Data behavior_board_global_ids = 22;
}
