syntax = "proto3";
package circuits_v2;

import "circuits/static/ev/circuit_type_data.proto";
import "circuits_v2/deprecated/DEPRECATED_circuit_type_data.proto";
import "circuits_v2/deprecated/DEPRECATED_dictionary_data.proto";
import "circuits_v2/deprecated/DEPRECATED_keyed_input_desc_data.proto";
import "circuits_v2/deprecated/DEPRECATED_keyed_output_desc_data.proto";
import "circuits_v2/input_desc_data.proto";
import "circuits_v2/output_desc_data.proto";

option csharp_namespace = "CircuitsV2.Protobuf";

message NodeDescData {
  string name = 2;
  repeated circuits.CircuitTypeData type_parameters = 10;
  repeated InputDescData inputs = 8;
  repeated OutputDescData outputs = 9;

  bytes DEPRECATED_id = 1;
  repeated DEPRECATED_CircuitTypeData DEPRECATED_type_parameters = 3;
  DEPRECATED_ListDictionaryData DEPRECATED_inputs_0 = 4;
  DEPRECATED_ListDictionaryData DEPRECATED_outputs_0 = 5;
  repeated DEPRECATED_KeyedInputDescData DEPRECATED_inputs_1 = 6;
  repeated DEPRECATED_KeyedOutputDescData DEPRECATED_outputs_1 = 7;
}
