syntax = "proto3";
package circuits_v2;
option csharp_namespace = "CircuitsV2.Protobuf";

import "core/guid_data.proto";

message ReplicatorRegistryData {	
  repeated ReplicatorRegistryEntryData replicator_entries = 1;
}

message ReplicatorRegistryEntryData {
  core.GuidData replicator_persistence_id = 1;
  int32 target_graph_id = 5;
  int32 reserved_copies = 3;
  repeated ReplicatedGraphData replicated_graph_data = 4;
  uint32 revision = 6;

  core.GuidData DEPRECATED_target_graph_id = 2;
}

message ReplicatedGraphData {
  core.GuidData base_graph_id = 1;
  repeated core.GuidData sub_graph_ids = 2; 
}
