syntax = "proto3";
package rec_room;

import "circuits_v2/inventory_item_equipment_slots_data.proto";
import "circuits_v2/persisted_value.proto";
import "circuits_v2/player_cloud_data.proto";
import "rec_room/persistence/player_save_version.proto";

option csharp_namespace = "RecRoom.Protobuf";

message PlayerSaveData {
  PlayerSaveVersion version = 1;
  circuits_v2.PlayerCloudData cloud_data = 9;
  circuits_v2.InventoryItemEquipmentSlotsData inventory_item_equipment_slots_configuration = 10;

  repeated circuits_v2.PersistedValue bools_DEPRECATED = 2;
  repeated circuits_v2.PersistedValue floats_DEPRECATED = 3;
  repeated circuits_v2.PersistedValue ints_DEPRECATED = 4;
  repeated circuits_v2.PersistedValue quaternions_DEPRECATED = 5;
  repeated circuits_v2.PersistedValue strings_DEPRECATED = 6;
  repeated circuits_v2.PersistedValue vector3s_DEPRECATED = 7;
  repeated circuits_v2.PersistedValue colors_DEPRECATED = 8;
}
