syntax = "proto3";
package rec_room;

import "rec_room/persistence/overridable_field_data.proto";

option csharp_namespace = "RecRoom.Protobuf";

message PlayerRoomRoleData {
  reserved 15;

  int32 DEPRECATED_role_id = 1;

  int32 DEPRECATED_role_rank = 2;

  bool DEPRECATED_is_role_active = 3;

  bool DEPRECATED_is_ag_role = 4;

  string role_name = 5;

  OverridableStringData name = 6;
  OverridableBoolData can_assign_roles = 7;
  OverridableIntData vote_kick_permission = 8;
  OverridableBoolData can_invite = 9;
  OverridableBoolData DEPRECATED_can_edit_circuits = 10;
  OverridableBoolData can_start_games = 11;
  OverridableBoolData can_talk = 12;
  OverridableBoolData can_print_photos = 13;
  OverridableBoolData can_edit_room_roles = 14;
  OverridableBoolData can_self_revive = 16;
  OverridableBoolData can_end_games_early = 17;
  OverridableBoolData can_change_game_mode = 21;
  OverridableBoolData can_use_maker_pen = 22;
  OverridableBoolData can_use_delete_all_button = 23;
  OverridableBoolData can_save_inventions = 24;
  OverridableBoolData disable_mic_auto_mute = 25;
  OverridableBoolData can_use_share_cam = 26;
  OverridableBoolData can_spawn_inventions = 28;
  OverridableBoolData can_spawn_consumables = 29;
  OverridableBoolData can_use_room_reset_button = 30;
  OverridableBoolData can_use_play_gizmos_toggle = 31;

  bool is_modified_by_player = 18;

  OverridableListStringData auto_assigned_game_roles = 19;

  int32 role_version = 20;

  string role_guid = 27;
}
