syntax = "proto3";
package circuits_v2;

import "circuits/shared/api/id_128_data.proto";
import "circuits/shared/utilities/soa_id_32_data.proto";
import "circuits_v2/messages/message_signature_data.proto";

option csharp_namespace = "CircuitsV2.Protobuf";

message MessagesStateData {
  circuits.SOAId32Data message_signature_ids = 1;
  repeated int32 message_signature_ref_counts = 2;
  repeated MessageSignatureData message_signatures = 3;
  repeated circuits.Id128Data message_event_definitions = 5;

  reserved 4;
}
